// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:pid": {
    params: {
      "pid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/:pid";
  };
  "./home.tsx": {
    id: "home";
    page: "/";
  };
  "./product.tsx": {
    id: "product";
    page: "/products/:pid";
  };
};